quadrantChart
    title Reach and engagement of snake games
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "Python Snake Game": [0.3, 0.6]
    "CLI Snake": [0.45, 0.23]
    "Snake CLI": [0.57, 0.69]
    "Snake Game": [0.78, 0.34]
    "Terminal Snake": [0.40, 0.34]
    "Snake Console": [0.35, 0.78]
    "Snake Command": [0.5, 0.6]
    "Our Target Product": [0.6, 0.7]
